### ISSUE TITLE
Initial version of WACZ IPFS Uploader SPA

### ISSUE THREAD

**Issue by RangerMauve** [webrecorder/wacz-uploader#1]
- [x] Sketch up UI using basic HTML/CSS
- [x] Get feedback on UI design from Sua
- [x] Initial uploading with auto-js-ipfs and auto-detecting
- [x] Add index.html and ui.js along side wacz file when uploading
- [ ] Add UI for configuring the parameters for "bring your own storage"
  - moved to https://github.com/webrecorder/wacz-uploader/issues/12

**Comment by SuaYoo** [comment]
Follow-up after initial: https://github.com/webrecorder/wacz-uploader/issues/18

**Comment by RangerMauve** [comment]
I'm going to move a bunch of the TODOs from this into separate issues.
