### ISSUE TITLE
Allow adding more files before starting upload

### ISSUE THREAD

**Issue by SuaYoo** [webrecorder/wacz-uploader#14]
Enable adding more files after choosing files in initial step:
<img width="477" alt="Screen Shot 2022-11-08 at 4 15 14 PM" src="https://user-images.githubusercontent.com/4672952/200687609-73e5feab-f6dd-4fb7-be1a-d43b2e91cd19.png">

**Comment by RangerMauve** [comment]
Closed by #9

**Comment by RangerMauve** [comment]
Maybe not clused by #9? :P I might have misunderstood.

**Comment by ikreymer** [comment]
> Maybe not clused by #9? :P I might have misunderstood.

Yeah, this is to have an 'Add Files...' button to be able to add more files after the initial drag selection.
Just offering more flexibility, if you missed a file, or you need to choose files from different directories on your hd, you can do that here
