### ISSUE TITLE
Add help / info section / page about how to create WACZ files

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/wacz-uploader#7]
Perhaps on the first page, in the space below, as a separate page, or help popup, we should list ways for users who just visit the site to be able to create WACZ files. Doesn't have to be super long, but maybe something like the following

###  How to Create Web Archives

Webrecorder offers several free tools for creating web archives in WACZ format, including:
- ArchiveWeb.page Browser Extension - Chrome/Edge/Brave Browser Extension for archiving exactly what you browse
- ArchiveWeb.page Express - All-in-one tool for creating a web archive, one page at a time.
- Browsertrix Crawler - A CLI application for running web crawls automatically and storing web archives.
- Browsertrix Cloud - A UI web app for running multiple web crawls through a simple interface

 Probably want to include a logo and link for each at the beginning of the line?

**Comment by Shrinks99** [comment]
I think we should list one way for people to create wacz files, preferably the easiest and most beginner-focused option.  If people are completely new to the concept we shouldn't present them with a bunch of options and ask people to evaluate what would meet their needs — that's a great thing to have somewhere else (our website) but not as part of a web app with a new user flow with the aim of introducing people to the concept.

I would nominate ArchiveWeb.page Express?  Seems to offer the fastest and most frictionless intro to the format.

**Comment by ikreymer** [comment]
Hm. Well ArchiveWeb.express has its own uploader, this is more designed for crawl-created archives from Browsertrix Crawler / Cloud, which is why wanted to list all of the options.
Maybe it makes sense for this to be under an expandable help text box (just <details> / <summary> block) so users can read about the different ways they can make web archives, rather than all just on the front page at once?

**Comment by Shrinks99** [comment]
> ArchiveWeb.express has its own uploader

Yes it does... It may not be the intended tool for the workflow of "I have a bunch of crawls and I want to create a website that hosts them all in one place" but it is a great tool for getting people to create a WACZ.  If the user story for this is "I'm a new user and I have no clue what a WACZ is?  Where can I get one of these" then those users actually have no use for the WACZ Uploader and we should direct them to a more suitable tool which offers a better user experience to introduce them to the ecosystem.

**Comment by Shrinks99** [comment]
Current copy proposal (will probably make some small tweaks here and there but this is what's in the repo now!)  Text level is aimed at a reasonably competent computer user who doesn't know what IPFS or HTTP actually do but does have the understanding of what "web archiving" generally is.

> Create an interactive, publicly accessible collection of archived webpages. The generated gallery will be available immediately in your browser, and in the browsers of tomorrow with IPFS — a peer-to-peer protocol that delivers files based on their contents.
>
> Never archived a website before? Try it with [ArchiveWeb.Page](https://express.archiveweb.page/)!

Hopefully any _truly_ new folks make it to the last line 🙃   I've considered most of this text pretty carefully but feedback is appreciated, especially on differentiating IPFS from HTTP in a way that people might actually understand.  Kind of a hard ask for half a sentence though!

**Comment by Shrinks99** [comment]
Closing this.  Marking as complete with the link to Express.ArchiveWeb.Page
